apiVersion: v1
kind: Pod
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  containers:
    - name: helloworld
      image: hello-world-api:latest
      imagePullPolicy: Never
      ports:
      - containerPort: 8080
